version: '3.4'

services:
  authblazor:
    image: ${DOCKER_REGISTRY-}authblazor
    build:
      context: .
      dockerfile: AuthBlazor/Dockerfile

  catalog:
    image: ${DOCKER_REGISTRY-}catalog
    build:
      context: .
      dockerfile: Catalog/Dockerfile

