version: '3.4'

services:
  # authblazor:
  #   environment:
  #     - CatalogApi=http://localhost:5209
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - ASPNETCORE_HTTP_PORTS=80
  #     - GRPC_PORT=8081
  #   ports:
  #     - "5109:80"
  #     - "6109:8081"
  #   volumes:
  #     - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
  #     - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
  catalog:
    environment:
      - IdentityUrl=http://authrazor
      - IdentityUrlExternal=http://localhost:5309
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - Port=80
    ports:
      - "5209:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  authrazor:
    environment:
      - CatalogApi=http://localhost:5209
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - Port=80
    ports:
      - "5309:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
